name: Deploy Vue Dist to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:    # 允許手動觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Build Vue project
      run: npm run build
      
    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dist/"
        target: "/var/www/html"  # 改成您的 Nginx 實際服務目錄
        strip_components: 1  # 這會移除 dist 資料夾本身，只複製其內容
