name: Deploy Vue Project to EC2

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 檢出當前的專案
      - name: Checkout code
        uses: actions/checkout@v2

      # 使用 SSH 同步 dist 資料夾到 EC2
      - name: Sync dist to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 IP，從 GitHub Secrets 獲取
          username: ubuntu           # EC2 使用者
          key: ${{ secrets.EC2_SSH_KEY }}  # SSH 私鑰，從 GitHub Secrets 獲取
          script: |
            # 將 dist 資料夾同步到 EC2 的 /var/www/html
            rsync -av --delete ./dist/ /var/www/html/
